name: barreled_annotation
description: Annotations for barreled_generator.
version: 0.1.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.6.1

dependencies:

dev_dependencies:
  barreled_lints:
