name: >
  Push version tags
description: >
  Generate and push version tags for each updated package.

runs:
  using: composite
  steps:
    - name: Create and push tags to the repository
      # Ignores errors caused by creating tags that already exist  (`|| true`).
      run: |
        melos exec -c 1 --no-private -- git tag \$MELOS_PACKAGE_NAME-v\$MELOS_PACKAGE_VERSION || true
        git push --tags
      shell: bash
