name: >
  Merge pull request
description: >
  Merges a pull request with admin privileges. Currently, this will always do
  a rebase merge.

# TODO: Add input for merge method (merge/rebase).
# TODO: Use --auto merge flag when repository is public
#   https://github.com/dependabot/fetch-metadata?tab=readme-ov-file#enabling-auto-merge
#   https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-auto-merge-for-pull-requests-in-your-repository#about-auto-merge

inputs:
  pull-request-url:
    description: URL of the pull request to merge.
    required: true
  repository:
    description: Repository to merge the pull request into.
    required: true
  github-token:
    description: GitHub access token.
    required: true
    
runs:
  using: composite
  steps:
    - name: Merge pull request
      run: |
        gh pr merge --rebase --admin ${{ inputs.pull-request-url }} --repo ${{ inputs.repository }}
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
