name: barreled_example
description: Example library using barreled.
version: 0.1.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.6.1

dependencies:
  barreled_annotation:
  meta: ^1.15.0

dev_dependencies:
  barreled:
  barreled_lints:
  build_runner: ^2.4.14
