name: exported_lints
description: "Static-analysis lints for all `exported` packages."
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.6.1

resolution: workspace

dependencies:
  very_good_analysis: ^7.0.0
