name: exported_lints
description: "Shared static-analysis configuration for all `exported` packages."
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.6.1

resolution: workspace

dependencies:
  very_good_analysis: ^7.0.0
