name: exported_example
description: Example library using barreled.
version: 0.2.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.6.1

dependencies:
  exported_annotation:
  meta: ^1.15.0

dev_dependencies:
  build_runner: ^2.4.14
  exported:
  exported_lints:
