name: >
  Version all workflow packages and create a PR
description: >
  Versions all packages in the workspace and create a PR with the new versions.

runs:
  using: composite
  steps:
    - name: Run melos version
      run: |
        melos version --all --yes --no-git-tag-version
      shell: bash

    - name: Create pull request
      uses: peter-evans/create-pull-request@v7
      with:
        title: |
          chore(version): automatic versioning
        body: |
          Incremented all package versions.
        branch: version-${{ github.run_id }}
        delete-branch: true
        token: ${{ env.GITHUB_TOKEN }}
        sign-commits: true
