name: >
  Automated versioning
description: >
  Versions all workspace packages create a pull request with the new versions.

runs:
  using: composite
  steps:
    - name: Run melos version
      run: |
        melos version --yes --no-git-tag-version --no-changelog
      shell: bash

    - name: Update changelogs
      run: |
        melos run release:release-changelog --no-select
        git add .
        git commit -m "chore: update changelogs after versioning" || echo "No changes to commit"
      shell: bash

    - name: Create pull request
      uses: peter-evans/create-pull-request@v7
      with:
        title: |
          chore: automated versioning
        body: |
          Increment package versions.
        branch: version-${{ github.run_id }}
        delete-branch: true
        token: ${{ env.GITHUB_TOKEN }}
        sign-commits: true
