name: >
  Automated versioning
description: >
  Versions all workspace packages create a pull request with the new versions.

runs:
  using: composite
  steps:
    - name: Run melos version
      run: |
        melos version --all --yes --no-git-tag-version
      shell: bash

    - name: Create pull request
      uses: peter-evans/create-pull-request@v7
      with:
        title: |
          chore: automated versioning
        body: |
          Increment package versions.
        branch: version-${{ github.run_id }}
        delete-branch: true
        token: ${{ env.GITHUB_TOKEN }}
        sign-commits: true
