builders:
  exported:
    import: package:exported/builder.dart
    builder_factories: [ barrelFileBuilder ]
    build_extensions: { $package$: [ .stub ] }
    required_inputs: [ .exported.json ]
    applies_builders: [ :exported_cache ]
    auto_apply: dependents
    build_to: source

  exported_cache:
    import: package:exported/builder.dart
    builder_factories: [ exportCacheBuilder ]
    build_extensions: { .dart: [ .exported.json ] }
    build_to: cache
