builders:
  exported:
    import: package:exported/builder.dart
    builder_factories: [ exportedBuilder ]
    build_extensions: { $package$: [ .stub ] }
    auto_apply: dependents
    build_to: source
