name: exported
description: Code generator for Dart-package barrel files.
version: 0.1.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.6.1

dependencies:
  analyzer: ">=6.0.0 <8.0.0"
  build: ^2.4.2
  collection: ^1.19.0
  dart_style: ^3.0.1
  exported_annotation:
  fast_immutable_collections: ^11.0.3
  file: ^7.0.1
  glob: ^2.1.3
  meta: ^1.15.0
  path: ^1.9.0
  source_gen: ^2.0.0
  yaml: ^3.1.3

dev_dependencies:
  build_test: ^2.2.3
  exported_lints:
  mocktail: ^1.0.4
  test: ^1.25.8
