targets:
  $default:
    builders:
      :barreled: { enabled: false }
      :barreled_exports: { enabled: false }

      json_serializable:
        enabled: true
        generate_for:
          - lib/src/model/*.dart
        options:
          any_map: true
          explicit_to_json: true

builders:
  barreled:
    import: package:barreled_generator/builder.dart
    builder_factories: [ barreledBuilder ]
    build_extensions: { $package$: [ barreled.stub ] }
    auto_apply: dependents
    build_to: source

  barreled_exports:
    import: package:barreled_generator/builder.dart
    builder_factories: [ barreledExportsBuilder ]
    build_extensions: { .dart: [ .barreled.json ] }
    auto_apply: dependents
    build_to: cache
    runs_before: [ :barreled ]
