name: barreled_generator
description: Code generator for Dart-package barrel files.
version: 0.1.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.6.1

dependencies:
  analyzer: ^6.11.0
  barreled_annotation:
  build: ^2.4.2
  collection: ^1.19.0
  dart_style: ^2.3.7
  file: ^7.0.1
  json_annotation: ^4.9.0
  glob: ^2.1.3
  path: ^1.9.0
  source_gen: ^1.5.0
  yaml: ^3.1.3

dev_dependencies:
  barreled_lints:
  build_runner: ^2.4.14
  build_test: ^2.2.3
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  test: ^1.25.8
